import {
  BasePageInfoResponse,
  BaseResponse,
  BaseThumbnail,
} from '~/client/types/base-response'

/**
 * Response type for YouTube Data API `channels`.
 * Official Docs: https://developers.google.com/youtube/v3/docs/channels/list
 */
export type ChannelsResponse = BaseResponse &
  BasePageInfoResponse & {
    /**
     * The result is stored as an array.
     */
    items: {
      kind: string
      etag: string
      id: string
      /**
       * Basic information about the channel.
       */
      snippet?: ChannelsResponseSnippet
      /**
       * Content information about the channel.
       */
      contentDetails?: ChannelsResponseContentDetail
      /**
       * Statistical information about the channel.
       */
      statistics?: ChannelsResponseStatistic
      /**
       * Privacy status information about the channel.
       */
      status?: ChannelsResponseStatus
      /**
       * Freebase topic information associated with the channel.
       * Freebase: An online database that was acquired by Google and later made public.
       */
      topicDetails?: ChannelsResponseTopicDetail
      /**
       * Branding information about the channel.
       */
      brandingSettings?: ChannelsResponseBrandingSetting
    }[]
  }

/**
 * Data type for the `snippet` part of YouTube Data API `channels`.
 */
export type ChannelsResponseSnippet = {
  /**
   * Channel title.
   */
  title: string
  /**
   * Description of the channel.
   */
  description: string
  /**
   * Custom URL.
   * Access the corresponding channel with `https://youtube.com/[Custom URL]`.
   */
  customUrl: string
  /**
   * Channel creation date.
   * Returned in ISO 8601 format (`YYYY-MM-DDThh:mm:ss.sZ`).
   */
  publishedAt: string
  thumbnails: BaseThumbnail
  /**
   * Country of the channel.
   */
  country: string

  defaultLanguage: string

  localized: {
    title: string
    description: string
  }
}

/**
 * Data type for the `contentDetails` part of YouTube Data API `channels`.
 */
export type ChannelsResponseContentDetail = {
  /**
   * Playlist IDs automatically generated by YouTube.
   */
  relatedPlaylists: {
    /**
     * Playlist ID for "Liked Videos".
     * If set to private, an empty string is returned.
     */
    likes: string
    /**
     * Playlist ID for "Uploaded Videos".
     */
    uploads: string
  }
}

/**
 * Data type for the `statistics` part of YouTube Data API `channels`.
 */
export type ChannelsResponseStatistic = {
  /**
   * Total view count of the channel.
   */
  viewCount: string
  /**
   * Number of subscribers to the channel.
   */
  subscriberCount: string
  /**
   * Whether the subscriber count is publicly visible.
   * `true`: Publicly visible / `false`: Not publicly visible
   */
  hiddenSubscriberCount: boolean
  /**
   * Number of videos uploaded to the channel.
   * Live streams are also included.
   * Only videos with a "public" visibility setting are counted.
   */
  videoCount: string
}

/**
 * Data type for the `topicDetails` part of YouTube Data API `channels`.
 */
export type ChannelsResponseTopicDetail = {
  /**
   * Freebase topic IDs.
   * It seems you can use the Freebase API to get more information about these topics.
   */
  topicIds: string[]
  /**
   * Categories of the topics.
   */
  topicCategories: string[]
}

/**
 * Data type for the `status` part of YouTube Data API `channels`.
 */
export type ChannelsResponseStatus = {
  /**
   * Privacy status of the channel.
   * - `private`: Private
   * - `public`: Public
   * - `unlisted`: Unlisted (probably)
   */
  privacyStatus: string
  /**
   * Indicates whether a YouTube username or Google+ account is linked to the channel.
   */
  isLinked: boolean
  /**
   * Unknown value.
   * Observed as `longUploadsUnspecified`.
   */
  longUploadsStatus: string
  /**
   * Whether the channel is designated for kids.
   */
  madeForKids: boolean
  selfDeclaredMadeForKids: boolean
}

/**
 * Data type for the `brandingSettings` part of YouTube Data API `channels`.
 */
export type ChannelsResponseBrandingSetting = {
  /**
   * Branding information for the channel page.
   */
  channel: {
    /**
     * Channel title.
     * Title length is limited to 15 full-width characters (or 30 half-width characters).
     */
    title: string
    /**
     * Channel description.
     */
    description: string
    /**
     * Keywords set for the channel.
     * If not set, this property is omitted.
     */
    keywords: string
    /**
     * Default tab name when viewers navigate to the channel page.
     * If not set, this property is omitted.
     */
    defaultTab: string
    /**
     * Google Analytics account ID for tracking traffic to the channel.
     * If not set, this property is omitted.
     */
    trackingAnalyticsAccountId: string
    /**
     * Video ID of the recommended video for unsubscribed viewers.
     */
    unsubscribedTrailer: string
    /**
     * Country of the channel.
     */
    country: string
  }
  image: {
    /**
     * Specifies the location of the banner image that YouTube uses
     * to generate banners of various sizes for the channel (probably).
     * Refer to the official Docs for more details.
     */
    bannerExternalUrl: string
  }
}
